Page Create
ThinLineIT/CtrlF_Frontend pull request #112
Opened 2021-10-25 09:52 UTC by JSH-data

Create Page Flow 작업 완료
#110 오류 해결
#106 작업 완료

2021-11-01 11:47 UTC, createhb21 approved these changes
확인했습니다.

2021-11-02 08:49 UTC, syg4806 requested changes

2021-11-02 08:49 UTC, syg4806 commented on yarn.lock
> +>>>>>>> e5cc749b9fea6078756d25817c618ef5075a9323
충돌이 나있는 코드인것같은데요..?

2021-11-02 08:49 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
> +  const showPageContent = (issue_id, title, status, convention, content) => {
`issue_id` -> `issueId `

2021-11-02 08:49 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
>  export default function IndexIndex() {
IndexIndex..? ㅎㅎ
다시 명명해볼까요

2021-11-02 08:49 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
>  export default function IndexIndex() {
ContentNavigator정도어떨까요?

2021-11-02 11:00 UTC, JSH-data commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
>  export default function IndexIndex() {
이부분은 제가 만든 부분이 아니라서 효범님과 상의 후 교체해보겠습니다

2021-11-02 11:02 UTC, JSH-data commented on yarn.lock
> +>>>>>>> e5cc749b9fea6078756d25817c618ef5075a9323
충돌이 있었던 부분이 맞습니다 ㅠ
제가 저 한 줄을 빼먹고 못지웠네요 테스트시 문제가 없어서 인지하지 못했습니다.. 수정하겠습니다!

2021-11-04 00:34 UTC, syg4806 approved these changes

2021-11-04 00:34 UTC, merged