topic create 생성
ThinLineIT/CtrlF_Frontend pull request #113
Opened 2021-10-25 10:32 UTC by createhb21

2021-11-03 06:26 UTC, JSH-data requested changes

2021-11-03 06:26 UTC, JSH-data commented on src/components/items/modal/AlertModal.jsx
> +  const { mTitle, aTitle, kTitle, issue는 } = titleObj;
앞에 알파벳 의미를 잘모르겠어요 ㅠ

2021-11-03 14:45 UTC, createhb21 commented on src/components/items/modal/AlertModal.jsx
> +  const { mTitle, aTitle, kTitle, issue는 } = titleObj;
주석 남겨놓겠습니다

2021-11-04 00:38 UTC, syg4806 requested changes

2021-11-04 00:38 UTC, syg4806 commented on src/utils/useModal.js
> +  let kTitle = ''; // korea title
약어는 공용적으로 정의한게 아니면 최대한 피하는게 좋습니다.
이렇게 주석을 다는 것 보다 애초에 modalTitle이라고 명명하시면 더 명확해집니다.
다시 명명해주세요..

2021-11-04 00:42 UTC, syg4806 commented
+ 충돌도 잡아주세요!

2021-11-04 00:45 UTC, createhb21 commented on src/utils/useModal.js
> +  let kTitle = ''; // korea title
넵!

2021-11-06 12:52 UTC, merged