Feature/drop menu
ThinLineIT/CtrlF_Frontend pull request #123
Opened 2021-11-22 05:01 UTC by JSH-data

#115 제작 완료

2021-11-22 08:52 UTC, syg4806 requested changes

2021-11-22 08:52 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +    const result = await issueApproveApi(issue.id);
issue가 approve가 되면 null 이고 에러같은게 발생하면 result가 들어있는 형태인가요?
그러면 error 로 표시하는게 적절해 보입니다

2021-11-22 08:52 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +      setIsFeatureClicked(true);
`setIsFeatureClicked`이게 `setIsModalOpen` 이랑 따로 관리되어야 하는 이유는 뭘까요?

2021-11-22 08:52 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +  };
`rejectIssue` 이건 소문자로시작.. `CancelIssue` 이건 대문자로 시작..

2021-11-22 13:38 UTC, JSH-data commented on src/components/items/modal/IssueDetailModal.jsx
> +      setIsFeatureClicked(true);
setIsFeatureClicked는 Issue 관련 API 없을 당시에 만들어 놓았던 변수 명입니다. 
그때 당시에는 Issue modal의 어떤 기능을 눌러도 권한이 없다는 표시를 해주어야 했으므로 "(이슈의) 기능이 클릭 되었는가?"라는 의미를 담아 만들었습니다. 지금 다시보니 의미가 명확하지 않은 것 같습니다. 
IsUnauthorized, setIsUnauthorized로 변경시키겠습니다!

2021-11-22 13:38 UTC, JSH-data commented on src/components/items/modal/IssueDetailModal.jsx
> +  };
수정하겠습니다!

2021-11-22 13:58 UTC, JSH-data commented on src/components/items/modal/IssueDetailModal.jsx
> +    const result = await issueApproveApi(issue.id);
제가 의미가 명확하게 바꿨었는데 반영이 안되어 있네요...! 수정했습니다!

2021-11-23 11:04 UTC, createhb21 approved these changes
👌

2021-11-24 08:36 UTC, syg4806 approved these changes

2021-11-24 12:18 UTC, merged