Image 추가 기능
ThinLineIT/CtrlF_Frontend pull request #125
Opened 2021-11-24 04:50 UTC by JSH-data

pages/img.jsx 파일로 컴포넌트를 만들었습니다.

2021-11-24 07:56 UTC, createhb21 approved these changes
에디터에 적용하니 잘 작동합니다

2021-11-25 00:36 UTC, syg4806 requested changes
함수명들도 명확히 해주세요.

2021-11-25 00:36 UTC, syg4806 commented on pages/img.jsx
> +    input_file.addEventListener('change', input_update);
카멜표기법!

2021-11-25 00:36 UTC, syg4806 commented on pages/img.jsx
> +    if (file && file.size < 5000000) {
`5000000` 상수로 분리

2021-11-25 00:36 UTC, syg4806 commented on pages/img.jsx
> +  const getUrl = async (file) => {
`uploadImage` 가 주 역할인듯 합니다

2021-11-25 00:36 UTC, syg4806 commented on pages/img.jsx
> +      imgAdding(res.data.image_url); // url이 반환됩니다.
`img` `image` 한가지 표현만 사용해주세요

2021-11-25 00:36 UTC, syg4806 commented on pages/img.jsx
> +    });
`file`을 전달받아서 실행하는 함수로 분리를 하고, 리스너에서는 해당 함수를 호출하는 형태로 하는게 좋을 듯 합니다.

2021-11-25 10:44 UTC, JSH-data commented on pages/img.jsx
> +    });
이건 이따 의견 다시 한 번 들어보고 반영해보겠습니다~!

2021-12-01 11:59 UTC, JSH-data commented on pages/img.jsx
> +    });
파일추가버튼을 눌러 이미지를 추가하는 경우 이벤트리스너를 통해서 파일의 첨부를 확인합니다.
이벤트 리스너가 변화를 감지하고 그에 해당하는 이벤트를 attachImage 함수의 인자로 넘겨주게 됩니다. 
이미지를 드롭해서 추가하는 경우에도 동일한 과정이 진행됩니다. 
하지만 두 이벤트 인자에서 이미지 담긴 위치에서 조금 차이가 발생합니다.
그래서 저는 이벤트를 감지하는 함수를 따로 두고(attachImage, dropImage)
API 호출 함수(uploadImage), URL을 에디터에 추가해주는 함수(imageAdding)를 각각 두었습니다.

제가 이해한것이 맞다면 윤권님이 요청하신 작업은 attachImage, dropImage를 통합하고 동일한 리스너에 이벤트를 걸어 놓는 것인데 제가 생각하기엔 함수를 각각 두는 것이 더 직관적인 것 같습니다..! 그래서 해당 요청 작업에 대해서는 별다른 수정을 하지 않았습니다!

혹시 제가 이해한게 틀렸다면 말씀해주세요! 다시 수정하겠습니다! 늦어서 죄송합니다 ㅠㅠ

2021-12-01 12:25 UTC, syg4806 approved these changes

2021-12-01 12:25 UTC, syg4806 commented on pages/img.jsx
> +  const LIMIT = 5000000;
5MB를 의도하신 거라면 5 * 1024 * 1024 가 정확합니다!

2021-12-01 12:25 UTC, syg4806 commented on pages/img.jsx
> +  const imageAdding = (url) => {
함수명 `insertImageUrl` 정도가 어떨까요?

2021-12-02 07:35 UTC, merged