Editor 컴포넌트 안의 버튼 기능 구현 부분을 Object화 시켜서 분리
ThinLineIT/CtrlF_Frontend pull request #126
Opened 2021-11-27 06:20 UTC by createhb21

기존의 약간의 의존성을 가지고 사용했던 insert-text-at-cursor 라이브러리는 제거했습니다.

이미지 기능 구현 부분도 추후에 승화님 작업 마무리 되시면 분리시켜놓겠습니다.

2021-11-28 07:55 UTC, syg4806 approved these changes
컨벤션같은거 수정하는 경우는 커밋을 따로 분리해주세요..!
리뷰하기 힘들어요 ㅠ

2021-11-28 07:57 UTC, syg4806 requested changes
`prettier` 가 코딩 컨벤션 설정하는 부분인 것 같은데, 이거는 프로젝트 전체단위로 동일하게 적용되어야 하는 부분 인 것 같아요. 이 pr에서는 적용하지 말고 프로젝트 전체에 적용하는 pr을 따로 만들어주세요

2021-11-30 09:21 UTC, JSH-data approved these changes

2021-12-01 12:34 UTC, syg4806 requested changes
음.. 제생각엔 이부분은 효율성보다는 가독성 높이는게 더 필요로 해보여요. 차라리 각 툴마다(버튼) 함수를 별개로 만들어서 처리하고 중복되는 부분을 함수로 분리해서 처리하는게 좋을 것 같습니다.

2021-12-01 12:34 UTC, syg4806 commented on src/utils/useEditorBtns.js
> +    const sStart = TextArea.selectionStart;
앞에 s는 select인가요? 그냥 selectionStart, selectionEnd정도 어떨까요?

2021-12-01 12:34 UTC, syg4806 commented on src/utils/useEditorBtns.js
> +    let keyBtn = this.useEditorBtns(key);
`keyBtn` -> `formatText` 어때요?

2021-12-01 12:34 UTC, syg4806 commented on src/utils/useEditorBtns.js
> +  static FIRST_ORDER_BTNS = ['H', 'Q', 'L', 'P', 'BL', 'NL', 'TL'];
`FIRST_ORDER_BTNS` First order..? 무슨 의미죠?

2021-12-02 10:03 UTC, createhb21 commented on src/utils/useEditorBtns.js
> +  static FIRST_ORDER_BTNS = ['H', 'Q', 'L', 'P', 'BL', 'NL', 'TL'];
재명명하겠습니다.!

2021-12-09 03:20 UTC, syg4806 approved these changes

2021-12-09 03:20 UTC, syg4806 commented on src/utils/useEditorBtns.js
> +  static NON_MAPPING_BTNS = [
`NON_MAPPING_BTNS` NON_MAPPING은 무슨뜻이죠..?

2021-12-09 03:35 UTC, createhb21 commented on src/utils/useEditorBtns.js
> +  static NON_MAPPING_BTNS = [
드래깅하고 버튼 클릭 시에 감싸주는 식의 태그가 아닌 버튼들입니다 
그런데 mapping이 감싸주다라는 의미가 아닌 것 같기도 하네요......

2021-12-09 06:19 UTC, merged