노트, 토픽 이름 수정 컴포넌트 제작
ThinLineIT/CtrlF_Frontend pull request #127
Opened 2021-11-27 07:42 UTC by JSH-data

삽질을 너무 많이 하다보니 조금 늦어졌습니다 ㅠ

+ rightClick에 효범님께서 해주시면 하는 작업을 적어두었습니다 확인 한 번 부탁드립니다.

2021-11-28 08:01 UTC, syg4806 requested changes

2021-11-28 08:01 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/rightClick.jsx
>      setShowHiddenModal(true);
`HiddenModal` ?! 은 무엇이죠..?

2021-11-28 09:38 UTC, JSH-data commented on src/components/items/button/ButtonMiddle.jsx
> +export default function ButtonMiddle({ text, methods }) {
중간 사이즈 버튼을 만들어서 재사용하려고 했었습니다...! 근데 다시 생각해보니 그냥 외부에서 width만 주는 방식으로 바꾸면 더 재사용을 할 수 있을거 같네요! 수정하겠습니다!

2021-11-28 09:39 UTC, JSH-data commented on src/components/items/notes/noteDetail/sideIndex/rightClick.jsx
>      setShowHiddenModal(true);
그 부분은 효범님이 작업하신 부분입니다! 임시로 잠시 만드신것 같습니다!

2021-11-29 02:47 UTC, createhb21 approved these changes
확인했습니다!

2021-12-01 12:36 UTC, syg4806 approved these changes

2021-12-02 07:29 UTC, merged