separation APIs (staging & production)
ThinLineIT/CtrlF_Frontend pull request #132
Opened 2021-12-13 07:14 UTC by createhb21

2021-12-16 08:07 UTC, syg4806 requested changes

2021-12-16 08:07 UTC, syg4806 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
NEXT의 의미는..?!
`STAGING_API_BASE_URL`
`RELEASE_API_BASE_URL`
정도가 좋을 듯 합니다.

2021-12-16 08:07 UTC, syg4806 commented on src/components/items/button/ButtonMiddle.jsx
> +export default function ButtonMiddle({ text, methods }) {
`Middle` 의 의미가 모호하네요..?

2021-12-16 08:07 UTC, syg4806 commented on src/components/items/button/ButtonMiddle.jsx
> +export default function ButtonMiddle({ text, methods }) {
사이즈인가요?

2021-12-16 08:07 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +  const setPageVersion_no = useSetRecoilState(issueDetailPageVersion_no);
카멜과 언더스코어 혼용은 좀..ㅠ

2021-12-16 08:07 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +    issueDetailPageVersion_no
ditto

2021-12-16 08:07 UTC, syg4806 commented on src/store/atom.js
> +export const issueDetailPageVersion_no = atom({
ditto

2021-12-16 08:07 UTC, syg4806 commented on src/utils/useFetch.js
> +  _BASE_URL = `http://testdeploy-dev.ap-northeast-2.elasticbeanstalk.com/api/${this.issue}/`;
왜 또 새로 정의하나요?

2021-12-16 08:57 UTC, createhb21 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
NEXT_PUBLIC_ 은 사용하는 Next.js에서의 네이밍 규칙이라서 바꾸지 못하는 걸로 알고 잇습니다.!

2021-12-20 04:38 UTC, syg4806 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
...? 상수명을 그렇게 정의해두었다구요..?

2021-12-20 04:40 UTC, createhb21 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
넵 .env 파일을 이용할 때 꼭 붙혀야 하는 접두사 같은 겁니다..!

2021-12-20 04:42 UTC, createhb21 commented on src/components/items/button/ButtonMiddle.jsx
> +export default function ButtonMiddle({ text, methods }) {
이부분은 승화님 저번 pr에서 올리신 내용인데, 제가 새로 pull받으면서 제 pr에도 새로운 추가 파일로 올라온 듯 싶습니다! 저번 승화님 pr에서 승화님이 수정하신 걸로 알고 있어서 따로 수정 없이 dev 브렌치에 올리고 충돌 해결할 때 승화님 작업하신대로 따라가면 될 듯 싶습니다.

2021-12-20 04:42 UTC, createhb21 commented on src/components/items/modal/IssueDetailModal.jsx
> +  const setPageVersion_no = useSetRecoilState(issueDetailPageVersion_no);
넵 수정하겠습니다

2021-12-20 04:43 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +    issueDetailPageVersion_no
수정하겠습니다

2021-12-20 04:43 UTC, createhb21 commented on src/store/atom.js
> +export const issueDetailPageVersion_no = atom({
수정하겠습니다

2021-12-20 04:43 UTC, createhb21 commented on src/utils/useFetch.js
> +  _BASE_URL = `http://testdeploy-dev.ap-northeast-2.elasticbeanstalk.com/api/${this.issue}/`;
이 부분도 승화님이 작업하신 부분이라 위에 내용과 동일합니다

2021-12-20 04:43 UTC, syg4806 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
환경변수의 네이밍 룰이네요.
"NEXT_PUBLIC_STAGING_API_BASE_URL"
"NEXT_PUBLIC_RELEASE_API_BASE_URL" 로가시죠

2021-12-20 04:44 UTC, createhb21 commented on .env.production
>  NEXT_PUBLIC_RELEASE_API_BASE_URL=https://ctrlfbe.link/api/
넵 수정하겠습니다

2021-12-21 13:25 UTC, merged