Page detail - making custom Image block and overflow-x hidden
ThinLineIT/CtrlF_Frontend pull request #137
Opened 2021-12-16 07:36 UTC by createhb21

2021-12-21 14:14 UTC, syg4806 requested changes

2021-12-21 14:14 UTC, syg4806 commented on src/utils/pageDetailFetch.js
> +      }notes/${id}/topics`
```
const NEXT_PUBLIC_API_BASE_URL = process.env.NODE_ENV === 'development'
          ? process.env.NEXT_PUBLIC_STAGING_API_BASE_URL
          : process.env.NEXT_PUBLIC_RELEASE_API_BASE_URL
```
그 환경변수쪽에 이런식으로 정의해두면 가져오는 곳에서 매번 이 로직을 검사하지 않아도 될 것 같은데 어떤가요?

2021-12-21 14:14 UTC, syg4806 commented on src/components/Markdown/Renderer/Renderer.jsx
> +  return <Image src={src} alt={src} width={477} />;
`477` 상수로분리..!

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +    const topicList = await topicListApi(noteId) //
`//`  지워주세용

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +    const pageList = await pageListApi(topicId) //
ditto `//`

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +    const pageList = await pageDetailApi(pageId, version_no) //
ditto `//`

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +    let { id, title, is_approved } = data;
`data` 가 토픽인거죠?

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
>    const showPageList = async (data) => {
이 한 함수에 너무 많은 기능이 포함된 것 같네요.. 모듈화를 더 해보시는게 좋을 듯 합니다.

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +          setPageData(pages);
pageData에 pages를.. pageList, pages, page, pageData 네가지가 혼용되는데 너무 명확하지 않습니다. 다시 정의해보세요.

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
>          document.getElementById(`page${pageId}`).click(); // 여기서 version_no를 체크해주는게 필요할 것 같습니다.
`// 여기서 version_no를 체크해주는게 필요할 것 같습니다.`
어떤걸 체크해줘야 한다는거죠?

2021-12-21 14:14 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +        is_approved == false && ifNotApprovedClicked('page');
`is_approved == false && ifNotApprovedClicked('page');` 이거는 받는 곳 이 없는 것 같은데요..?

2021-12-21 14:31 UTC, createhb21 commented on src/utils/use_pagination.js
> +        setHasMore(notes.length > 0);
유저가 스크롤 할 때마다 cursor 쿼리를 이용해서 새로운 30개의 노트를 api에 요청하는데, 만약 response 로 받아오는 노트의 개수가 0보다 크다면 hasmore의 값이 true가 되고 note가 더이상 없다면 hasMore이 false가 되어 api요청을 더이상 하지 않습니다 !

2021-12-21 14:33 UTC, createhb21 commented on src/utils/pageDetailFetch.js
> +      }notes/${id}/topics`
https://statamic.com/forum/2421-how-to-use-an-env-variable-in-a-conditio 참고해서 변경해보겠습니다!

2021-12-21 14:36 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
>    const showPageList = async (data) => {
동의합니다.. 예전에 처음 코드를 짤 때부터 좀 더 깔끔하게 짰다면 좋았을 것 같은데... 우선 모듈화를 좀 더 해보겠습니다.

2021-12-21 14:36 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +          setPageData(pages);
넵 !

2021-12-21 14:39 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
>          document.getElementById(`page${pageId}`).click(); // 여기서 version_no를 체크해주는게 필요할 것 같습니다.
이슈 페이지에서 넘어올 때 저 함수가 실행되는데, 이제는 pageId뿐만 아니라 version_no까지 반영한 디테일한 페이지로 넘어가야 하는 걸로 알고 있어서 적어놨습니다.

2021-12-21 14:52 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +        is_approved == false && ifNotApprovedClicked('page');
is_approved == false라면 ifNotApprovedClicked('page')를 실행해라 라는 의미의 코드입니다. 다만 밑의 코드가 
is_approved == true라면 ... 이라서
가독성이 좋도록 코드를 합치겠습니다.

2021-12-21 15:36 UTC, createhb21 commented on src/utils/pageDetailFetch.js
> +      }notes/${id}/topics`
아 이게 제가 알기론 .env.process 파일과 .env.develope 파일에 똑같은 네이밍을 주고 위의 if문은 따로 안돌려도 
npm run dev 할  때는 .env.develope를 이용하고 npm run start는 .env.process를 사용하는 걸로 알고 있습니다.
예를 들어 두 파일 모두 
NEXT_PUBLIC_API_BASE_URL=https:// ...... 
이런식으로만 주는데, 값만 다르게 설정해놓으면 됩니다.
우선 위 내용이 확실하게 맞는지 좀 더 확인해보겠습니다.

2021-12-21 16:22 UTC, JSH-data approved these changes

2021-12-22 07:57 UTC, syg4806 commented on src/utils/use_pagination.js
> +        setHasMore(notes.length > 0);
더 가져온게 있다는 의미인건가요?

2021-12-22 07:59 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +        is_approved == false && ifNotApprovedClicked('page');
아하 JS에서는 유독 그런식의 사용이 자주 보이는 것 같더군요.. 알겠습니다..!

2021-12-22 08:03 UTC, createhb21 commented on src/utils/use_pagination.js
> +        setHasMore(notes.length > 0);
note_list 컴포넌트에서 위 함수를 사용해 note, hasMore, error을 받아옵니다.
또한 note_list에서는 받아온 hasMore의 불린값을 검사하고 true일시에만 api요청을 더 합니다. false라면 불필요한 api요청을 하지 않습니다. 이런 의미로 사용하고 있습니다 @syg4806

2021-12-22 08:04 UTC, syg4806 approved these changes

2021-12-22 08:04 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +    let { id, title, is_approved } = data;
topic으로 rename해주세요..!

2021-12-22 08:04 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/ContentNavigator.jsx
> +    //
`//` ?!?!?!?!

2021-12-22 08:16 UTC, merged