Change IssueList Page Scroll Event Method to IntersectionObserver
ThinLineIT/CtrlF_Frontend pull request #148
Opened 2022-01-18 15:10 UTC by JSH-data

기존 이슈 페이지의 무한 스크롤 방식을 IntersectionObserver로 변경하였습니다.

2022-01-20 07:55 UTC, createhb21 requested changes

2022-01-23 03:01 UTC, JSH-data commented on pages/issue.jsx
> +      await setPageCount(endCount);
1. react의 seState 속성 때문에 그렇습니다.
2. pageCount는 endCount 변수로 계속 참조되어 사용되고 있습니다. state로 관리하는게 제일 좋은 방법이라고 생각하는데 혹시 추천해주실만한 방법이 있으신가요?

2022-01-23 03:04 UTC, JSH-data commented on pages/issue.jsx
> +      await setPageCount(endCount);
1번은 조금 더 알맞게 수정하도록 하겠습니다

2022-01-24 03:16 UTC, createhb21 approved these changes

2022-01-30 01:21 UTC, syg4806 requested changes

2022-01-30 01:21 UTC, syg4806 commented on pages/issue.jsx
> +      let endCount = pageCount + 30;
fetchCount를 30씩 늘리는 것 보다 전달받은 issue 의 갯수로 증가시키는 것이 좋을 것 같습니다

2022-01-31 09:35 UTC, JSH-data commented on pages/issue.jsx
> +      let endCount = pageCount + 30;
이 부분에 대해서 고민 좀 해보겠습니다...!

2022-02-07 13:03 UTC, merged