login & signUp
ThinLineIT/CtrlF_Frontend pull request #20
Opened 2021-07-25 10:37 UTC by JSH-data

떨리는 첫 PR입니다...

분명 어딘가 문제가 있을테지만 한 번 날려봅니다...!

2021-08-02 11:59 UTC, syg4806 requested changes

2021-08-02 11:59 UTC, syg4806 commented on pages/login.jsx
> +    <div className="test">
test 코드가 남아있는 것 같습니다.

2021-08-02 11:59 UTC, syg4806 commented on pages/signUp.jsx
> +  const OVERLAP = useRecoilValue(isOverlaped)
변수 선언 순서를 가독성좋게 변경해주세요

2021-08-02 12:01 UTC, syg4806 approved these changes

2021-08-03 03:26 UTC, createhb21 requested changes
확인했습니다.

2021-08-03 06:14 UTC, createhb21 approved these changes

2021-08-03 07:28 UTC, syg4806 requested changes

2021-08-03 13:04 UTC, JSH-data commented on pages/signUp.jsx
> +
삭제했습니다

2021-08-03 13:04 UTC, JSH-data commented on src/components/Login/LoginForm.jsx
> +  }
event 입니다 수정했습니다

2021-08-03 13:04 UTC, JSH-data commented on src/components/Login/LoginForm.jsx
> +    const data = {
반영하여 수정했습니다

2021-08-03 13:05 UTC, JSH-data commented on src/components/SignUp/SignUpFormEmail.jsx
> +    const [Email, setEmail] = useRecoilState(emailAtom);
제 실수입니다 수정했습니다.

2021-08-03 13:06 UTC, JSH-data commented on src/components/SignUp/SignUpFormPassword.jsx
> +      const IsNickNameOverlap = await nickNameOverlap(nickName);
상수가 아니라 API 요청후 성공시 반환된 객체입니다. 수정했습니다.

2021-08-07 03:50 UTC, syg4806 approved these changes
LGTM 
Api  상수명만 변경하고 머지해주세요

2021-08-07 03:50 UTC, syg4806 commented on .env.local
> +NEXT_PUBLIC_BASE_API = "http://testdeploy-dev.ap-northeast-2.elasticbeanstalk.com/api"
`PUBLIC_BASE_API`
`MOCK_PUBLIC_BASE_API`
정도로 나누시는게 좋을 것 같네요

2021-08-07 04:48 UTC, merged