main feature
ThinLineIT/CtrlF_Frontend pull request #21
Opened 2021-08-03 05:23 UTC by createhb21

progress
1. get note list API data and set up in main view
2. note details are using with getStaticeProps & setStaticPath on Next.js
3. some modal components are updated
4. side buttons are now works nice
5. main view CSS

2021-08-03 05:41 UTC, createhb21 commented on src/component/items/notes/note_list.jsx
> +                )} ${`styles.color_((${note.id} / 5) % 15)`}`}
여기 ${`styles.color_((${note.id} / 5) % 15)`} 부분 삭제하시고 실행하셔야 될 것 같습니다. 노트 색깔과 관련된 클래스인데 작동에 계속 애를 먹어서 우선 없애고 추후 좀 더 찾아보면서 추가하려고 했으나, 실수로 삭제 안한 상태로 PR을 한 것 같습니다😥

2021-08-03 07:29 UTC, syg4806 commented on src/component/items/notes/note_list.jsx
> +                )} ${`styles.color_((${note.id} / 5) % 15)`}`}
삭제하고 푸시하시면 이 pr에 해당 커밋 추가됩니다!

2021-08-03 08:06 UTC, createhb21 commented on src/component/items/notes/note_list.jsx
> +                )} ${`styles.color_((${note.id} / 5) % 15)`}`}
확인했습니다! 재커밋하고 푸시했습니다.

2021-08-03 08:06 UTC, syg4806 requested changes

2021-08-03 08:06 UTC, syg4806 commented on src/component/items/sidebar/toggle.jsx
> +  const handleButtonReject = () => {
`handleSomething`의 명명보다는 `onSomething`은 어때요?
ex) `onReject` `onApprove`

2021-08-03 08:06 UTC, syg4806 commented on src/component/layout/topbar.jsx
> +const Topbar = memo(() => {
`memo`는 이 기능을 표현하기 부적절한 듯 합니다

2021-08-03 08:06 UTC, syg4806 commented on src/component/layout/topbar.jsx
> +  function handleSearch(e) {
[ditto] onSearch는 어떤가요

2021-08-03 08:06 UTC, syg4806 commented on src/component/layout/topbar.jsx
> +    handleSearch(e);
왜 `onClick`으로 한번 감싸서 다시 사용을 하나요? 바로 `handleSearch`를 호출하면 안되나요?

2021-08-03 08:06 UTC, syg4806 commented on src/hooks/use_note_search.js
> +
삭제될 기능일 것 같아 따로 리뷰하지 않겠습니다.

2021-08-03 08:06 UTC, syg4806 commented on src/hooks/use_note_search.js
> +
코드 남기고 싶으시면 주석으로 다음버전에 사용될 기능이라고 적어놔주세요

2021-08-03 08:06 UTC, syg4806 commented on src/store/atom.js
> +  key: 'MyNotes',
`My`라는 접두어를 사용해야하나요?

2021-08-03 08:09 UTC, syg4806 requested changes

2021-08-03 08:09 UTC, syg4806 commented on src/component/items/notes/note_list.jsx
> +
추후에 사용될 코드인가요?
주석으로 남겨놓는 이유를 적어주세요

2021-08-03 08:09 UTC, syg4806 commented on src/component/items/notes/note_list.jsx
> +
여러줄 주석이라면 
`/* ... */` 를 이용해주세요

2021-08-03 08:15 UTC, createhb21 commented on src/component/items/modal/add_note_modal.jsx
> +  };
버튼의 value가 'Login 하러 가기'여서 그런 것 같습니다, 함수명을 더욱 구체화시키는 건 어떨까요 ?

2021-08-03 08:16 UTC, syg4806 commented on src/component/items/modal/add_note_modal.jsx
> +  };
넵 함수명을 구체화해주세요

2021-08-03 08:17 UTC, syg4806 commented on src/component/items/modal/add_note_modal.jsx
> +  };
`closeModal`이라 하면, 단순히 모달을 닫는다고만 예상되는데, 정작 내용은 signup으로 연결되어 있어서 그렇습니다!
함수명은 해당 함수가 어떤 작업을 하는지 명확히 표현해줘야 좋습니다!

2021-08-07 04:00 UTC, syg4806 requested changes
리뷰 반영해주시고, 승화님꺼 머지되면, 충돌잡고 연결시켜서 테스트후에 머지해주세요

2021-08-07 14:39 UTC, syg4806 approved these changes

2021-08-09 05:34 UTC, JSH-data commented
component 폴더를 components로 바꿔주실 수 있나요?!

2021-08-09 05:40 UTC, createhb21 commented
넵 바꾸겠습니다 !

2021년 8월 9일 (월) 오후 2:34, JSH-data ***@***.***>님이 작성:

> component 폴더를 components로 바꿔주실 수 있나요?!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ThinLineIT/CtrlF_Frontend/pull/21#issuecomment-894962817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATEHIKJVALETVJOHMI3NZ53T35SIFANCNFSM5BOCFSIQ>
> .
>

2021-08-09 11:24 UTC, merged