SVG color Setting
ThinLineIT/CtrlF_Frontend pull request #58
Opened 2021-08-31 15:17 UTC by JSH-data

2021-09-02 11:34 UTC, createhb21 approved these changes
👍

2021-09-03 07:20 UTC, syg4806 requested changes

2021-09-03 07:20 UTC, syg4806 commented on src/constant/issueTypes.js
> +];
type과 action으로 분리시키는게 좋을 것 같아요

2021-09-03 07:20 UTC, syg4806 commented on src/constant/issueTypes.js
> +];
그러면 const IssueCard 쪽 로직도 간단해질 듯 하네요

2021-09-03 07:55 UTC, JSH-data commented on src/constant/issueTypes.js
> +];
수정했습니다!

2021-09-03 12:16 UTC, syg4806 requested changes

2021-09-03 12:16 UTC, syg4806 commented on src/constant/issueTypes.js
> +export const ACTIONS = ['CREATE', 'UPDATE', 'DELETE'];
https://www.sohamkamani.com/javascript/enums/
enum을 이용하면 더 좋을 것 같네요! ㅎㅎ

2021-09-04 10:37 UTC, JSH-data commented on src/constant/issueTypes.js
> +export const ACTIONS = ['CREATE', 'UPDATE', 'DELETE'];
이걸 이제 봤네요 ㅠㅠ 확인해서 반영해보겠습니다!

2021-09-07 01:23 UTC, syg4806 approved these changes

2021-09-07 01:23 UTC, merged