Markdown Renderer & Editor
ThinLineIT/CtrlF_Frontend pull request #63
Opened 2021-09-03 15:11 UTC by createhb21

2021-09-06 03:20 UTC, JSH-data approved these changes

2021-09-08 15:10 UTC, syg4806 requested changes

2021-09-08 15:10 UTC, syg4806 commented on src/components/items/notes/noteDetail/markdownEditor.jsx
> +  const onChangeStatus = (status) => {
status를 enum으로 관리하면 더 좋을 듯합니다.

2021-09-08 15:10 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
>    const setMyPageContent = useSetRecoilState(pageContent);
[ditto] 저희 프로젝트에 myPage라는 개념이 있나요?

2021-09-08 15:26 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/index_index.jsx
>    const setMyPageContent = useSetRecoilState(pageContent);
변수명 수정하도록 하겠습니다 !

2021-09-10 12:15 UTC, syg4806 approved these changes
충돌 잡고 머지해주세요

2021-09-14 05:14 UTC, merged