Feature/issue modal
ThinLineIT/CtrlF_Frontend pull request #64
Opened 2021-09-07 04:00 UTC by JSH-data

2021-09-07 09:03 UTC, createhb21 approved these changes
확인했습니다.

2021-09-08 15:20 UTC, syg4806 requested changes

2021-09-08 15:20 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +      // API 개발 완료시 교체 예정
주석은 보통 설명하려는 코드 위에 작성합니다!

2021-09-08 15:20 UTC, syg4806 commented on src/components/issue/NoAuthentification.jsx
> +    setIsModalFeature(false);
`IsModalFeature` 가 무엇을 의미하죠? 현재 모달이 열려있는지를 관리하는 것인가요?
그렇다면 `IsModalOpend` 정도가 어떨까요?

2021-09-08 15:20 UTC, syg4806 commented on src/components/items/modal/IssueDetailModal.jsx
> +    setModal(false);
이게 모달 닫는건가?! 그럼 isModalFeature는 무엇을 의미하죠..?!

2021-09-09 05:07 UTC, JSH-data commented on src/components/issue/NoAuthentification.jsx
> +    setIsModalFeature(false);
네 알겠습니다!

2021-09-09 05:07 UTC, JSH-data commented on src/components/items/modal/IssueDetailModal.jsx
> +    setModal(false);
변수명을 전체적으로 다시 고려해보겠습니다!

2021-09-10 12:18 UTC, syg4806 approved these changes

2021-09-11 08:47 UTC, merged