Feature/issue tag
ThinLineIT/CtrlF_Frontend pull request #65
Opened 2021-09-08 08:09 UTC by JSH-data

#62 를 Tag 기능에 적용하였습니다.

2021-09-08 15:31 UTC, syg4806 requested changes

2021-09-08 15:31 UTC, syg4806 commented on src/components/issue/IssueTagBtn.jsx
> +  const unSelect = () => {
rename to `unselect`

2021-09-08 15:31 UTC, syg4806 commented on src/components/issue/IssueTagBtn.jsx
> +    if (filterList.includes(name) && selected === true) setCheckState(false);
filterList.includes(name) 인지를 확인해야하나요?

2021-09-09 05:15 UTC, JSH-data commented on src/components/issue/IssueTagBtn.jsx
> +    if (filterList.includes(name) && selected === true) setCheckState(false);
반드시 확인해야 합니다. 
만약 filterList에 해당 인스턴스가 있고(filterList.includes(name), 선택된 상황(selected === true, IssueTagInput 컴포넌트에 담긴 버튼)이 충족한다면 
이 버튼들은 선택이 되어 있지 않은 디자인을 적용시켜야 하기 때문입니다. 
마찬가지로 filterList에 들어가있으며, IssueTagList 컴포넌트에 존재한다면 이는 선택된 디자인이 적용되어야 하기 때문에 그 부분을 고려한 것입니다. 

변수명이 selected라 조금 헷갈릴 우려가 있을거 같습니다. selected를 isInputList 같은 내용을 담도록 바꿔보겠습니다.

2021-09-10 12:20 UTC, syg4806 approved these changes

2021-09-10 12:20 UTC, syg4806 approved these changes

2021-09-11 16:29 UTC, merged