Feature/login check
ThinLineIT/CtrlF_Frontend pull request #70
Opened 2021-09-09 07:09 UTC by JSH-data

#61 함수 제작

2021-09-10 12:35 UTC, syg4806 requested changes

2021-09-10 12:35 UTC, syg4806 commented on src/utils/loginCheck.js
> +export const loginCheck = (setJwt) => {
rename to `checkLogin`

2021-09-12 09:48 UTC, createhb21 approved these changes

2021-09-12 21:32 UTC, syg4806 approved these changes

2021-09-16 04:37 UTC, merged