preparing Modal components, gloabal working in functionally and resolve conflicts
ThinLineIT/CtrlF_Frontend pull request #72
Opened 2021-09-16 07:35 UTC by createhb21

2021-09-16 13:41 UTC, syg4806 requested changes
multi-line comment와 주석을 한 이유에 대해서 작성해주세요
ex)
```
/* TODO: 0.2.1 버전에 활성화 될 기능입니다.
...
*/

2021-09-16 13:41 UTC, syg4806 commented on src/components/items/modal/modal_preparing.jsx
> +  const setModalHiiden = useSetRecoilState(preparingModal);
[typo] setModalHiiden

2021-09-16 13:41 UTC, syg4806 commented on src/components/items/notes/noteDetail/detail_contents.jsx
> +  };
`dropdownActive`가 `modalToggle`을 충분히 대체할 수 있을 것 같아보이네요.
`modalToggle`을 따로 사용해야하는 이유가 있나요?

2021-09-16 13:41 UTC, syg4806 commented on src/components/items/notes/noteDetail/detail_contents.jsx
> +            <span onClick={onChangeContent}>수정된 사람</span>
이부분은 mocklist를 만들어서 동적으로 생성되게끔 수정해주세요
+ 이번 버전에 들어가지 않는 기능으로 파악되는데 주석처리로 해두셔도 괜찮습니다.

2021-09-16 13:41 UTC, syg4806 commented on src/components/items/notes/noteDetail/sideIndex/addBtn.jsx
> -    setTextareaPlaceholder('요청 내용 설명');
추후에 사용될 기능아닌가요? 주석이 아니라 지워도 되는건가요?

2021-09-18 14:38 UTC, createhb21 commented on src/components/items/notes/noteDetail/detail_contents.jsx
> +  };
첫번째 클릭 시에는 드롭다운이 되고, 두번째 클릭 시에는 드롭다운이 다시금 올라가게끔 의도했습니다!

2021-09-18 14:41 UTC, createhb21 commented on src/components/items/notes/noteDetail/sideIndex/addBtn.jsx
> -    setTextareaPlaceholder('요청 내용 설명');
위 부분은 따로 빼서 저장해두었습니다..! 그런데 모달 관련된 코드들을 추후에 props를 넘겨주는 형식으로 최적화시킬 수 있겠다 싶어 고려중이긴합니다.

2021-09-18 15:02 UTC, merged