디자인 수정
ThinLineIT/CtrlF_Frontend pull request #77
Opened 2021-09-27 11:14 UTC by createhb21

2021-09-28 08:19 UTC, JSH-data approved these changes

2021-09-30 01:28 UTC, syg4806 requested changes

2021-09-30 01:28 UTC, syg4806 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +  const setMyPageList = useSetRecoilState(pageList);
MyPage 가 무엇이죠..?
`setMyPageList` -> `setPageList`

2021-09-30 01:28 UTC, syg4806 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +  const setData = useSetRecoilState(noteDetailData);
`setData` -> `setNoteDetailData`

2021-09-30 01:36 UTC, createhb21 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +  const setMyPageList = useSetRecoilState(pageList);
넵!

2021-09-30 01:39 UTC, merged

2021-09-30 01:40 UTC, createhb21 commented on src/components/items/notes/noteDetail/note_detail.jsx
> +  const setData = useSetRecoilState(noteDetailData);
수정 완료했습니다!